### ISSUE TITLE
RenderStateNotation build failure on GitHub CI

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#135]
After the recent GitHub CI virtual image upgrade from 20220119.1 -> 20220123.1, my PSO archive CI checks started failing with the Python error messages quoted below.

Just thought to mention (it's not an important thing for us), I'm thinking that the way of generating those header files might not be optimal for your development purposes, as generated headers are only created on project configuration, and not when the source files change.

CI error log:

2022-01-27T09:54:44.0364101Z [9/9] Completed 'DiligentTools-download'
2022-01-27T09:54:44.0409817Z Using build configuration file 
2022-01-27T09:54:44.0410673Z custom_configure_build() function not found in 
2022-01-27T09:54:44.0411900Z Target Platform: Linux
2022-01-27T09:54:44.0413619Z D3D11_SUPPORTED:  FALSE
2022-01-27T09:54:44.0414219Z D3D12_SUPPORTED:  FALSE
2022-01-27T09:54:44.0414784Z GL_SUPPORTED:     FALSE
2022-01-27T09:54:44.0415354Z GLES_SUPPORTED:   FALSE
2022-01-27T09:54:44.0415931Z VULKAN_SUPPORTED: TRUE
2022-01-27T09:54:44.0416493Z METAL_SUPPORTED:  FALSE
2022-01-27T09:54:44.0417206Z CMake Warning at 3rdparty/DiligentCore/CMakeLists.txt:376 (message):
2022-01-27T09:54:44.0417968Z   gcc 9.0 and above seemingly produce invalid binary code with O2 and O3
2022-01-27T09:54:44.0418926Z   optimization levels.  Optimization in release configurations will be
2022-01-27T09:54:44.0419725Z   downgraded to O1.  It is strongly recommended to use clang.
2022-01-27T09:54:44.0420204Z 
2022-01-27T09:54:44.0420467Z 
2022-01-27T09:54:44.0475529Z -- SPIRV-Cross: Finding Git version for SPIRV-Cross.
2022-01-27T09:54:44.0511162Z -- Found Git: /usr/bin/git (found version "2.34.1") 
2022-01-27T09:54:44.0530763Z -- SPIRV-Cross: Git hash: 4652366a
2022-01-27T09:54:44.0774736Z -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
2022-01-27T09:54:44.8996665Z HLSL support is disabled. Vulkan backend will not be able to consume SPIRV bytecode generated from HLSL.
2022-01-27T09:54:44.8997819Z GLSLang is not being built. Vulkan backend will only be able to consume SPIRV byte code.
2022-01-27T09:54:46.9065995Z Collecting libclang
2022-01-27T09:54:46.9394054Z   Downloading libclang-13.0.0-py2.py3-none-manylinux1_x86_64.whl (14.5 MB)
2022-01-27T09:54:47.5958410Z Installing collected packages: libclang
2022-01-27T09:54:47.9205677Z Successfully installed libclang-13.0.0
2022-01-27T09:54:49.1054562Z Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (2.10.1)
2022-01-27T09:54:49.5825120Z Traceback (most recent call last):
2022-01-27T09:54:49.5826603Z   File "/home/runner/work/xxxx/3rdparty/DiligentTools/RenderStateNotation/scripts/cxx_generator.py", line 51, in <module>
2022-01-27T09:54:49.5827640Z     main()
2022-01-27T09:54:49.5828695Z   File "/home/runner/work/xxxx/3rdparty/DiligentTools/RenderStateNotation/scripts/cxx_generator.py", line 47, in main
2022-01-27T09:54:49.5829851Z     generate_file(file, os.path.join(args.dir, generated_filename(file)))
2022-01-27T09:54:49.5831103Z   File "/home/runner/work/xxxx/3rdparty/DiligentTools/RenderStateNotation/scripts/cxx_parser.py", line 150, in generate_file
2022-01-27T09:54:49.5832623Z     translation_unit = index.parse(input_filename, args=['-std=c++14'])
2022-01-27T09:54:49.5833827Z   File "/home/runner/.local/lib/python3.8/site-packages/clang/cindex.py", line 2721, in parse
2022-01-27T09:54:49.5834933Z     return TranslationUnit.from_source(path, args, unsaved_files, options,
2022-01-27T09:54:49.5836222Z   File "/home/runner/.local/lib/python3.8/site-packages/clang/cindex.py", line 2836, in from_source
2022-01-27T09:54:49.5837330Z     raise TranslationUnitLoadError("Error parsing translation unit.")
2022-01-27T09:54:49.5838349Z clang.cindex.TranslationUnitLoadError: Error parsing translation unit.

**Comment by MikhailGorobets** [comment]
@speedym  Hi, Milan
You can checkout to this branch https://github.com/DiligentGraphics/DiligentTools/tree/generator_fix

**Comment by speedym** [comment]
Yup, that fixed the issue. Thanks! :)
